version: '2'

services:
    core:
        restart: always
        expose:
            - "8083"
        ports:
            - "8083:8083"
        build:  https://github.com/tiroso/docker-fhem-sqlite.git#master
        image: docker-fhem-sqlite/latest
        privileged: true
        volumes:
            - core-config:/opt/fhem/config
            - core-log:/opt/fhem/log
        command: bash /opt/fhem/start.sh
        networks:
            - smarthome_internal

networks:
    smarthome_internal:

volumes:
    core-config:
    core-log:
