version: '2'

services:
    portainer:
        expose:
            - "9000"
        ports:
            - "9000:9000"
        image: portainer/portainer
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
    fhem-server:
        restart: always
        ports:
            - "8083:8083"
            - "2121:2121"
        build:  https://github.com/tiroso/docker.git#master:fhem-server
        image: tiroso/fhem-server
        privileged: true
        volumes:
            - fhem-server-config:/opt/fhem/config
            - fhem-server-log:/opt/fhem/log
            - fhem-server-core:/opt/fhem/FHEM
            - fhem-server-www:/opt/fhem/www
        command: bash /start.sh
        networks:
            - smarthome_internal
    smartvisu-fhem:
        restart: always
        ports:
            - "80:80"
        volumes:
            - smartvisu-config:/var/www/html/config
            - smartvisu-widgets:/var/www/html/widgets
            - smartvisu-pages:/var/www/html/pages
        build:  https://github.com/tiroso/docker.git#master:smartvisu-fhem
        image: tiroso/smartvisu
        networks:
            - smarthome_internal

networks:
    smarthome_internal:

volumes:
    portainer_data:
    fhem-server-config:
    fhem-server-log:
    fhem-server-core:
    fhem-server-www:
    smartvisu-config:
    smartvisu-widgets:
    smartvisu-pages:
