version: '2'

services:
    fhem:
        restart: always
        expose:
            - "8083"
        ports:
            - "8083:8083"
        build:  https://github.com/tiroso/docker-fhem-sqlite.git\#master
        volumes:
            - fhem-server-config:/opt/fhem/config
            - fhem-server-log:/opt/fhem/log
        networks:
            - smarthome_internal

networks:
    smarthome_internal:
        driver: bridge

volumes:
    fhem-server-config:
    fhem-server-log:
