version: '2'

services:
    portainer:
        expose:
            - "9000"
        ports:
            - "9000:9000"
        image: portainer/portainer
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
    fhem-server:
        restart: always
        ports:
            - "8083:8083"
            - "2121:2121"
        build:  https://github.com/tiroso/docker.git#master:fhem-server
        image: tiroso/fhem-server
        privileged: true
        volumes:
            - fhem-server:/opt/fhem
        command: bash /start.sh
        networks:
            - smarthome_internal
    smartvisu-fhem:
        restart: always
        ports:
            - "8080:80"
        volumes:
            - smartvisu-fhem:/var/www/html
        build:  https://github.com/tiroso/docker.git#master:smartvisu-fhem
        image: tiroso/smartvisu-fhem
        networks:
            - smarthome_internal

networks:
    smarthome_internal:

volumes:
    portainer_data:
    fhem-server:
    smartvisu-fhem:
